### ISSUE TITLE
老哥能分享下训veri_wild的参数吗

### ISSUE THREAD

**Issue by q147258134** [DTennant/reid_baseline_with_syncbn#1]
这数据集实在是太太太太大了，小实验室跑不起
老哥能分享下训练这个数据集的参数或者pth文件吗

**Comment by DTennant** [comment]
训练 veriwild的参数就是https://github.com/DTennant/reid_baseline_with_syncbn/blob/master/configs/veriwild.yml，pth我稍后上传百度云。。

**Comment by DTennant** [comment]
链接：https://pan.baidu.com/s/1Vml5XV_103wr7sgWfOz9Kg 
提取码：hfwn 

要训练的话，你还需要把数据集中的图片重命名成0001_c014_00001.jpg（vehicleid_cameraid_imageid.jpg）。

**Comment by wangzhiyuanking** [comment]
> 链接：https://pan.baidu.com/s/1Vml5XV_103wr7sgWfOz9Kg
> 提取码：hfwn
> 
> 要训练的话，你还需要把数据集中的图片重命名成0001_c014_00001.jpg（vehicleid_cameraid_imageid.jpg）。
老哥，您好，我是刚reID入门的学生，请问VeRi-Wild数据集中图片如何重命名？是否可以提供一下脚本文件？谢谢
