### ISSUE TITLE
train on VeRI776 dataset

### ISSUE THREAD

**Issue by ggyybb** [DTennant/reid_baseline_with_syncbn#12]
您好，可以提一下怎么用veri776数据集训练这个模型么，十分感谢！

**Comment by DTennant** [comment]
https://github.com/michuanhaohao/reid-strong-baseline/issues/145 看起来你好像已经解决这个问题了是吗，哈哈哈

**Comment by Schanppi** [comment]
> 您好，可以提一下怎么用veri776数据集训练这个模型么，十分感谢！

请问解决这个问题了吗
