### ISSUE TITLE
使用VehicleID进行训练

### ISSUE THREAD

**Issue by guoguoguilai** [DTennant/reid_baseline_with_syncbn#2]
Vehicle数据集的QUERY和GALLERY怎么选呢？我个人把其中一个测试集里的800个id分别选出一个作为QUERY，其他的作为GALLERY。然后我对所有图片按照格式重命名为：“00000001_c0000_00000005.jpg”。当我对比使用veri.yml训练的时候，提示如下：
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set .
如果我注释掉FP16，代码会一直停留在等待状态（后来发现改小batch_size就好了）但我发现训练速度有点慢呀，3块1080Ti训练一个epoch需要1个多小时，这速度正常吗？

**Comment by DTennant** [comment]
多卡的fp16训练还有点问题。。VehicleID这个数据集很大，所以跑起来速度很慢，这是正常的

**Comment by guoguoguilai** [comment]
> 多卡的fp16训练还有点问题。。VehicleID这个数据集很大，所以跑起来速度很慢，这是正常的

敢问大佬Veri-wild训练了多久呀？

**Comment by DTennant** [comment]
https://github.com/DTennant/reid_baseline_with_syncbn/blob/master/outputs/veriwild/log.txt
你可以看这里的log，40个epoch跑了两天
