### ISSUE TITLE
中断训练后，如何恢复训练呢？

### ISSUE THREAD

**Issue by guoguoguilai** [DTennant/reid_baseline_with_syncbn#3]
我在train.py中load之后，出现：RuntimeError: Error(s) in loading state_dict for DataParallelWithCallback:
	Missing key(s) in state_dict: "module.base.conv1.weight", "module.base.bn1.weight", "module.base.bn1.bias", "module.base.bn1.running_mean", "module.base.bn1.running_var", "module.base.layer1.0.conv1.weight", "module.base.layer1.0.bn1.weight", "module.base.layer1.0.bn1.bias", "module.base.layer1.0.bn1.running_mean", "module.base.layer1.0.bn1.running_var", "module.base.layer1.0.conv2.weight", "module.base.layer1.0.bn2.weight", "module.base.layer1.0.bn2.bias", "module.base.layer1.0.bn2.running_mean", "module.base.layer1.0.bn2.running_var", "module.base.layer1.0.conv3.weight", "module.base.layer1.0.bn3.weight", "module.base.layer1.0.bn3.bias", "module.base.layer1.0.bn3.running_mean", "module.base.layer1.0.bn3.running_var", "module.base.layer1.0.downsample.0.weight", "module.base.layer1.0.downsample.1.weight", "module.base.layer1.0.downsample.1.bias", "module.base.layer1.0.downsample.1.running_mean", "module.base.layer1.0.downsample.1.running_var", "module.base.layer1.1.conv1.weight", "module.base.layer1.1.bn1.weight", "module.base.layer1.1.bn1.bias", "module.base.layer1.1.bn1.running_mean", "module.base.layer1.1.bn1.running_var", "module.base.layer1.1.conv2.weight", "module.base.layer1.1.bn2.weight", "module.base.layer1.1.bn2.bias", "module.base.layer1.1.bn2.running_mean", "module.base.layer1.1.bn2.running_var", "module.base.layer1.1.conv3.weight", "module.base.layer1.1.bn3.weight", "module.base.layer1.1.bn3.bias", "module.base.layer1.1.bn3.running_mean", "module.base.layer1.1.bn3.running_var", "module.base.layer1.2.conv1.weight", "module.base.layer1.2.bn1.weight", "module.base.layer1.2.bn1.bias", "module.base.layer1.2.bn1.running_mean", "module.base.layer1.2.bn1.running_var", "module.base.layer1.2.conv2.weight", "module.base.layer1.2.bn2.weight", "module.base.layer1.2.bn2.bias", "module.base.layer1.2.bn2.running_mean", "module.base.layer1.2.bn2.running_var", "module.base.layer1.2.conv3.weight", "module.base.layer1.2.bn3.weight", "module.base.layer1.2.bn3.bias", "module.base.layer1.2.bn3.running_mean", "module.base.layer1.2.bn3.running_var", "module.base.layer2.0.conv1.weight", "module.base.layer2.0.bn1.weight", "module.base.layer2.0.bn1.bias", "module.base.layer2.0.bn1.running_mean", "module.base.layer2.0.bn1.running_var", "module.base.layer2.0.conv2.weight", "module.base.layer2.0.bn2.weight", "module.base.layer2.0.bn2.bias", "module.base.layer2.0.bn2.running_mean", "module.base.layer2.0.bn2.running_var", "module.base.layer2.0.conv3.weight", "module.base.layer2.0.bn3.weight", "module.base.layer2.0.bn3.bias", "module.base.layer2.0.bn3.running_mean", "module.base.layer2.0.bn3.running_var", "module.base.layer2.0.downsample.0.weight", "module.base.layer2.0.downsample.1.weight", "module.base.layer2.0.downsample.1.bias", "module.base.layer2.0.downsample.1.running_mean", "module.base.layer2.0.downsample.1.running_var", "module.base.layer2.1.conv1.weight", "module.base.layer2.1.bn1.weight", "module.base.layer2.1.bn1.bias", "module.base.layer2.1.bn1.running_mean", "module.base.layer2.1.bn1.running_var", "module.base.layer2.1.conv2.weight", "module.base.layer2.1.bn2.weight", "module.base.layer2.1.bn2.bias", "module.base.layer2.1.bn2.running_mean", "module.base.layer2.1.bn2.running_var", "module.base.layer2.1.conv3.weight", "module.base.layer2.1.bn3.weight", "module.base.layer2.1.bn3.bias", "module.base.layer2.1.bn3.running_mean", "module.base.layer2.1.bn3.running_var", "module.base.layer2.2.conv1.weight", "module.base.layer2.2.bn1.weight", "module.base.layer2.2.bn1.bias", "module.base.layer2.2.bn1.running_mean", "module.base.layer2.2.bn1.running_var", "module.base.layer2.2.conv2.weight", "module.base.layer2.2.bn2.weight", "module.base.layer2.2.bn2.bias", "module.base.layer2.2.bn2.running_mean", "module.base.layer2.2.bn2.running_var", "module.base.layer2.2.conv3.weight", "module.base.layer2.2.bn3.weight", "module.base.layer2.2.bn3.bias", "module.base.layer2.2.bn3.running_mean", "module.base.layer2.2.bn3.running_var", "module.base.layer2.3.conv1.weight", "module.base.layer2.3.bn1.weight", "module.base.layer2.3.bn1.bias", "module.base.layer2.3.bn1.running_mean", "module.base.layer2.3.bn1.running_var", "module.base.layer2.3.conv2.weight", "module.base.layer2.3.bn2.weight", "module.base.layer2.3.bn2.bias", "module.base.layer2.3.bn2.running_mean", "module.base.layer2.3.bn2.running_var", "module.base.layer2.3.conv3.weight", "module.base.layer2.3.bn3.weight", "module.base.layer2.3.bn3.bias", "module.base.layer2.3.bn3.running_mean", "module.base.layer2.3.bn3.running_var", "module.base.layer3.0.conv1.weight", "module.base.layer3.0.bn1.weight", "module.base.layer3.0.bn1.bias", "module.base.layer3.0.bn1.running_mean", "module.base.layer3.0.bn1.running_var", "module.base.layer3.0.conv2.weight", "module.base.layer3.0.bn2.weight", "module.base.layer3.0.bn2.bias", "module.base.layer3.0.bn2.running_mean", "module.base.layer3.0.bn2.running_var", "module.base.layer3.0.conv3.weight", "module.base.layer3.0.bn3.weight", "module.base.layer3.0.bn3.bias", "module.base.layer3.0.bn3.running_mean", "module.base.layer3.0.bn3.running_var", "module.base.layer3.0.downsample.0.weight", "module.base.layer3.0.downsample.1.weight", "module.base.layer3.0.downsample.1.bias", "module.base.layer3.0.downsample.1.running_mean", "module.base.layer3.0.downsample.1.running_var", "module.base.layer3.1.conv1.weight", "module.base.layer3.1.bn1.weight", "module.base.layer3.1.bn1.bias", "module.base.layer3.1.bn1.running_mean", "module.base.layer3.1.bn1.running_var", "module.base.layer3.1.conv2.weight", "module.base.layer3.1.bn2.weight", "module.base.layer3.1.bn2.bias", "module.base.layer3.1.bn2.running_mean", "module.base.layer3.1.bn2.running_var", "module.base.layer3.1.conv3.weight", "module.base.layer3.1.bn3.weight", "module.base.layer3.1.bn3.bias", "module.base.layer3.1.bn3.running_mean", "module.base.layer3.1.bn3.running_var", "module.base.layer3.2.conv1.weight", "module.base.layer3.2.bn1.weight", "module.base.layer3.2.bn1.bias", "module.base.layer3.2.bn1.running_mean", "module.base.layer3.2.bn1.running_var", "module.base.layer3.2.conv2.weight", "module.base.layer3.2.bn2.weight", "module.base.layer3.2.bn2.bias", "module.base.layer3.2.bn2.running_mean", "module.base.layer3.2.bn2.running_var", "module.base.layer3.2.conv3.weight", "module.base.layer3.2.bn3.weight", "module.base.layer3.2.bn3.bias", "module.base.layer3.2.bn3.running_mean", "module.base.layer3.2.bn3.running_var", "module.base.layer3.3.conv1.weight", "module.base.layer3.3.bn1.weight", "module.base.layer3.3.bn1.bias", "module.base.layer3.3.bn1.running_mean", "module.base.layer3.3.bn1.running_var", "module.base.layer3.3.conv2.weight", "module.base.layer3.3.bn2.weight", "module.base.layer3.3.bn2.bias", "module.base.layer3.3.bn2.running_mean", "module.base.layer3.3.bn2.running_var", "module.base.layer3.3.conv3.weight", "module.base.layer3.3.bn3.weight", "module.base.layer3.3.bn3.bias", "module.base.layer3.3.bn3.running_mean", "module.base.layer3.3.bn3.running_var", "module.base.layer3.4.conv1.weight", "module.base.layer3.4.bn1.weight", "module.base.layer3.4.bn1.bias", "module.base.layer3.4.bn1.running_mean", "module.base.layer3.4.bn1.running_var", "module.base.layer3.4.conv2.weight", "module.base.layer3.4.bn2.weight", "module.base.layer3.4.bn2.bias", "module.base.layer3.4.bn2.running_mean", "module.base.layer3.4.bn2.running_var", "module.base.layer3.4.conv3.weight", "module.base.layer3.4.bn3.weight", "module.base.layer3.4.bn3.bias", "module.base.layer3.4.bn3.running_mean", "module.base.layer3.4.bn3.running_var", "module.base.layer3.5.conv1.weight", "module.base.layer3.5.bn1.weight", "module.base.layer3.5.bn1.bias", "module.base.layer3.5.bn1.running_mean", "module.base.layer3.5.bn1.running_var", "module.base.layer3.5.conv2.weight", "module.base.layer3.5.bn2.weight", "module.base.layer3.5.bn2.bias", "module.base.layer3.5.bn2.running_mean", "module.base.layer3.5.bn2.running_var", "module.base.layer3.5.conv3.weight", "module.base.layer3.5.bn3.weight", "module.base.layer3.5.bn3.bias", "module.base.layer3.5.bn3.running_mean", "module.base.layer3.5.bn3.running_var", "module.base.layer4.0.conv1.weight", "module.base.layer4.0.bn1.weight", "module.base.layer4.0.bn1.bias", "module.base.layer4.0.bn1.running_mean", "module.base.layer4.0.bn1.running_var", "module.base.layer4.0.conv2.weight", "module.base.layer4.0.bn2.weight", "module.base.layer4.0.bn2.bias", "module.base.layer4.0.bn2.running_mean", "module.base.layer4.0.bn2.running_var", "module.base.layer4.0.conv3.weight", "module.base.layer4.0.bn3.weight", "module.base.layer4.0.bn3.bias", "module.base.layer4.0.bn3.running_mean", "module.base.layer4.0.bn3.running_var", "module.base.layer4.0.downsample.0.weight", "module.base.layer4.0.downsample.1.weight", "module.base.layer4.0.downsample.1.bias", "module.base.layer4.0.downsample.1.running_mean", "module.base.layer4.0.downsample.1.running_var", "module.base.layer4.1.conv1.weight", "module.base.layer4.1.bn1.weight", "module.base.layer4.1.bn1.bias", "module.base.layer4.1.bn1.running_mean", "module.base.layer4.1.bn1.running_var", "module.base.layer4.1.conv2.weight", "module.base.layer4.1.bn2.weight", "module.base.layer4.1.bn2.bias", "module.base.layer4.1.bn2.running_mean", "module.base.layer4.1.bn2.running_var", "module.base.layer4.1.conv3.weight", "module.base.layer4.1.bn3.weight", "module.base.layer4.1.bn3.bias", "module.base.layer4.1.bn3.running_mean", "module.base.layer4.1.bn3.running_var", "module.base.layer4.2.conv1.weight", "module.base.layer4.2.bn1.weight", "module.base.layer4.2.bn1.bias", "module.base.layer4.2.bn1.running_mean", "module.base.layer4.2.bn1.running_var", "module.base.layer4.2.conv2.weight", "module.base.layer4.2.bn2.weight", "module.base.layer4.2.bn2.bias", "module.base.layer4.2.bn2.running_mean", "module.base.layer4.2.bn2.running_var", "module.base.layer4.2.conv3.weight", "module.base.layer4.2.bn3.weight", "module.base.layer4.2.bn3.bias", "module.base.layer4.2.bn3.running_mean", "module.base.layer4.2.bn3.running_var", "module.bottleneck.weight", "module.bottleneck.bias", "module.bottleneck.running_mean", "module.bottleneck.running_var", "module.classifier.weight". 
	Unexpected key(s) in state_dict: "state", "param_groups". 
我需要做些什么吗

**Comment by lipond** [comment]
楼主，你确定作者能看懂中文？

**Comment by guoguoguilai** [comment]
> 楼主，你确定作者能看懂中文？

哈哈，我是看作者在上一个issue里用的中文才提问的

**Comment by DTennant** [comment]
我在写的时候没考虑中断的问题。。不过看你的问题应该是多gpu的问题，你可以参考https://www.zhihu.com/question/67726969 这个知乎问题下的回答解决
